# Generated by Django 5.1.7 on 2025-08-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='current_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='playback_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='queue_data',
            field=models.JSONField(default=list),
        ),
    ]
